title: Icons
status: wip
context:
    icons:
        - id: arrow-double-left
        - id: arrow-double-right
        - id: arrow-down
        - id: arrow-left-stem
        - id: arrow-left
        - id: arrow-right-stem
        - id: arrow-right
        - id: arrow-up
        - id: calendar
        - id: cog
        - id: cross-circle
        - id: cross
        - id: document
        - id: download
        - id: elipsis
        - id: email
        - id: exclamation-mark
        - id: facebook
        - id: fast-forward
        - id: flag
        - id: flickr
        - id: hamburger
        - id: home
        - id: information
        - id: instagram
        - id: letter
        - id: linkedin
        - id: magnifying-glass-zoom-in
        - id: magnifying-glass-zoom-out
        - id: magnifying-glass
        - id: mail-opened
        - id: mail-unopened
        - id: minus
        - id: mouse
        - id: padlock-open
        - id: padlock-opened
        - id: padlock
        - id: paperless
        - id: pause
        - id: people
        - id: person
        - id: play
        - id: plus
        - id: print
        - id: prize-unclaimed
        - id: prize
        - id: question-mark
        - id: reverse
        - id: rewind
        - id: scroll
        - id: share
        - id: smartphone
        - id: speechbubble-left
        - id: speechbubble-right
        - id: speechbubble-text-left
        - id: speechbubble-text-right
        - id: speechbubbles
        - id: star
        - id: stop
        - id: telephone
        - id: tick
        - id: twitter
        - id: typetalk
        - id: upload
        - id: youtube
